import re
from fastapi import APIRouter, HTTPException
from models.schemas import (
    CodeGenerateRequest, CodeGenerateResponse,
    CodeRunRequest, CodeRunResponse,
    CodeExplainRequest, CodeExplainResponse,
)
from services.ollama_client import ollama_chat
from services.code_runner import run_python_code, format_output_for_speech
from services.prompts import CODE_TO_PYTHON_SYSTEM, ERROR_EXPLAIN_SYSTEM

router = APIRouter()


def _clean_code(raw: str) -> str:
    """
    Strips any markdown fences or stray explanation the LLM may add.
    Ensures we get only executable Python.
    """
    # Remove ```python ... ``` or ``` ... ``` fences
    raw = re.sub(r"```(?:python)?\s*", "", raw)
    raw = re.sub(r"```", "", raw)
    # Remove lines that look like explanations (start with #, Note:, etc.)
    lines = raw.splitlines()
    code_lines = []
    for line in lines:
        stripped = line.strip()
        # Keep blank lines and actual code; skip prose-only lines
        if stripped.startswith("Note:") or stripped.startswith("Explanation:"):
            continue
        code_lines.append(line)
    return "\n".join(code_lines).strip()


@router.post("/code/generate", response_model=CodeGenerateResponse)
async def generate_code(req: CodeGenerateRequest):
    """
    Takes transcribed audio text (Hinglish spoken request) and returns
    executable Python code generated by llama3.2.
    """
    if not req.audio_text or not req.audio_text.strip():
        raise HTTPException(status_code=400, detail="audio_text cannot be empty")

    # Build a focused, strict prompt so the LLM only returns code
    user_prompt = (
        f"Convert this to Python code: {req.audio_text.strip()}\n\n"
        "Return ONLY raw executable Python code. "
        "No explanation. No markdown. No backticks. No comments unless inline."
    )

    msgs = [{"role": "user", "content": user_prompt}]

    try:
        raw = await ollama_chat(CODE_TO_PYTHON_SYSTEM, msgs)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"LLM error: {str(e)}")

    code = _clean_code(raw)

    if not code:
        raise HTTPException(
            status_code=422,
            detail="LLM ne valid code generate nahi kiya. Dobara try karo."
        )

    # TTS-friendly intro text
    speech_prompt = (
        f"Maine yeh Python code banaya hai aapke liye. "
        f"Ab isse chalate hain aur output dekhte hain."
    )

    return CodeGenerateResponse(code=code, speech_prompt=speech_prompt)


@router.post("/code/run", response_model=CodeRunResponse)
async def run_code(req: CodeRunRequest):
    """
    Executes Python code safely in a subprocess.
    Returns stdout, stderr, success flag, and a TTS-ready Hinglish summary.
    """
    if not req.code or not req.code.strip():
        raise HTTPException(status_code=400, detail="code cannot be empty")

    stdout, stderr, success = await run_python_code(req.code, timeout=10)
    speech_output = format_output_for_speech(stdout, stderr, success)

    return CodeRunResponse(
        stdout=stdout,
        stderr=stderr,
        success=success,
        speech_output=speech_output,
    )


@router.post("/code/explain-error", response_model=CodeExplainResponse)
async def explain_error(req: CodeExplainRequest):
    """
    Takes the Python code + error message and returns a plain Hinglish
    explanation suitable for TTS / screen readers.
    """
    if not req.error or not req.error.strip():
        raise HTTPException(status_code=400, detail="error cannot be empty")

    user_prompt = (
        f"Yeh Python code tha:\n{req.code}\n\n"
        f"Aur yeh error aaya:\n{req.error}\n\n"
        "Is error ko Hinglish mein explain karo aur batao kaise theek karein. "
        "Plain text only. Koi markdown nahi. 2-3 sentences max."
    )

    msgs = [{"role": "user", "content": user_prompt}]

    try:
        explanation = await ollama_chat(ERROR_EXPLAIN_SYSTEM, msgs)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"LLM error: {str(e)}")

    return CodeExplainResponse(explanation=explanation.strip())